[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "pyCameraModel"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0 OR MIT"

[tool.hatch.version]
path = "src/pyCameraModel/__about__.py"
[tool]
